### ISSUE TITLE
Auth token should be removed from local storage on sign out

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#130]
The auth token saved in local storage can be used even when the user is signed out.

The sign out option should trigger a function to delete the token.

**Comment by groovecoder** [comment]
This is supposed to be in the chrome-extension, right?

**Comment by groovecoder** [comment]
Cleaning up issues ... @jdungan: is this fixed in the new extension code?

**Comment by jdungan** [comment]
Yes.  The token is removed in both Firefox and Chrome ... but I have some work to do on Firefox to get the event recognized on an already opened widget.

**Comment by groovecoder** [comment]
Is there a separate issue open for that? I.e., can we close this one?

**Comment by jdungan** [comment]
Your choice.  I'm trying to fix it now. Maybe close this one and re-open codesy/chrome-extension#67

**Comment by jdungan** [comment]
Fixed now in codesy extension jdungan/chrome-extension 7e65bf8870a260e393b0ba8ba39dc4f3c692f156
