### ISSUE TITLE
Change bid widget to link to claim form

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#162]
Do https://github.com/codesy/codesy/issues/161 first.

As a user looking at a closed issue, show me a link (i.e., not a form) to the claim form page on codesy, so that I can submit my claim.

**Comment by groovecoder** [comment]
@jdungan Right now we're doing the oppose of this - we're showing a "Claim the payout:" form directly in the widget. We want to keep that behavior, and close this?

**Comment by jdungan** [comment]
Hmm. Sending users to a claim form might be better. There's not much room to explain the claim process on the widget.

**Comment by jdungan** [comment]
The claim form is in the widget.  Once claim is submitted, widget shows link to claim status.
