### ISSUE TITLE
claim-by-bid url is not working

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#164]
Steps to reproduce:
1. Create a bid
2. Go to that bid's `claim-by-bid` url. (e.g., http://codesy-stage.herokuapp.com/claim/confirmation?bid=2)

Expected results:
See the `confirm_claim.html` template.

Actual results:
404

**Comment by jdungan** [comment]
I think you need an 's' ...

'''router.register(r'claims', views.ClaimViewSet)

r'^claim/confirmation\?bid=(?P<bid>\d+)$','''

**Comment by groovecoder** [comment]
The rest_framework router url's are for the plain 'ViewSet' routes. The `custom_endpoint_url_patterns` are for custom urls like the `ConfirmClaim` view.

**Comment by jdungan** [comment]
I changed it to claims and it worked.

**Comment by groovecoder** [comment]
It's showing you the confirm_claim template? Not just the "Claim List" page?

![claim-list-url](https://cloud.githubusercontent.com/assets/71928/6744621/036dade4-ce7a-11e4-9d4c-27f9a400ef07.png)

**Comment by jdungan** [comment]
Never mind.... I see my mistake.
