### ISSUE TITLE
When a user claims payout for an issue, notify the bidders who offered on the issue that they can vote on the claim

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#165]
Add a `post_save` signal handler to `Claim` to email all bidders with an offer > 0.

Email:
<user> has claimed payout for <issue>.
They have provided <evidence> as evidence of their fix.

Please approve or reject your payout here:
<vote-add>

**Comment by jdungan** [comment]
Isn't this is the same as #238?

**Comment by groovecoder** [comment]
Done.
