### ISSUE TITLE
Claim link is ugly

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#195]
Problem:  If you have made a claim, a link to the claim is added to the bid widget.  If you click on the link you get a DRF response.   We need to direct the user to a codesy page showing the claim.

**Comment by groovecoder** [comment]
The claim link should go to a new url in a new tab:
`/claim/{id}` which should be in `urls.py` routed to a new `views.GetClaim.as_view()` like the `views.GetBid.as_view()`

**Comment by groovecoder** [comment]
I fixed up the `ClaimViewSet` class to use `TemplateHTMLRenderer` so that we show the `claim_detail.html` template at `/claims/{id}`. This branch now needs to show the claim details in the template.

**Comment by groovecoder** [comment]
The template should include:
### Universal
* Claimant
* Issue URL
* Created Date
* Evidence URL
* Status
* X of Y approved (votes)
* Closing Date (Created Date + 30 days)

### For claimant
* Evidence URL Edit (only until there are votes)

### For bidders
* Vote form
