### ISSUE TITLE
Starting a claim shows DRF default 201 response template

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#196]
Steps to reproduce:
1. Bid on a GitHub issue
2. Go back to the issue
3. Enter claim evidence URL
4. Click "Claim"

Expected results:
Redirect/refresh to "You have claimed" widget view

Actual results:
DRF default 201 response template

**Comment by jdungan** [comment]
Here are thoughts from hack night:

![image1](https://cloud.githubusercontent.com/assets/1707538/12837319/076dd846-cb87-11e5-8641-4d8c66c2c902.JPG)
![image2](https://cloud.githubusercontent.com/assets/1707538/12837320/076ed6d8-cb87-11e5-9719-d2e982f17b49.JPG)

**Comment by groovecoder** [comment]
This is fixed.
