### ISSUE TITLE
Cannot save credit card

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#252]
Steps to reproduce:
1. Install extension
2. Sign in
3. Connect CC

Expected Results:
Page refreshes with successful card message

Actual Results:
Nothing; 403 response to the AJAX form submission with response:
```
{"detail":"CSRF Failed: CSRF token missing or incorrect."}
```

**Comment by jdungan** [comment]
Fixing this will depend on #253 because the cc form has been moved to an includes template
