### ISSUE TITLE
Adding an issue breaks the widget display

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#270]
STR:
1. Add a new issue on GitHub

Expected Results:
Show the codesy widget on the newly-created issue

Actual results:
```
ProgrammingError at /bid-for-url/

column auctions_bid.created does not exist
LINE 1: ...ns_bid"."ask_match_sent", "auctions_bid"."offer", "auctions_...
```

**Comment by groovecoder** [comment]
![codesy-fail](https://cloud.githubusercontent.com/assets/71928/14302671/1c7b0d82-fb69-11e5-857d-1a70942353cf.png)

**Comment by groovecoder** [comment]
![giphy](https://cloud.githubusercontent.com/assets/71928/14302692/4045944e-fb69-11e5-82b8-63fe90a97049.gif)

**Comment by jdungan** [comment]
Are you sure your db is migrated?  The payment branch works for me

**Comment by jdungan** [comment]
Can you test this after the payments PR?

**Comment by groovecoder** [comment]
![giphy](https://cloud.githubusercontent.com/assets/71928/14542834/b0b28608-0256-11e6-8ed3-2ff323dee254.gif)
