### ISSUE TITLE
Update styling

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#302]
The Foundation templating/styling is a hodge-podge. We should at least update the styling with a consistent color scheme and some better UI components. (Not everything needs to be callout.)

**Comment by groovecoder** [comment]
Planning to go with [Tango Desktop Project "Aluminum" color scheme](https://en.wikipedia.org/wiki/Tango_Desktop_Project#Palette) ...

![tango-aluminum](https://cloud.githubusercontent.com/assets/71928/15099760/7bad26e4-1524-11e6-9df3-2efeb24804c7.png)

Should go fine with Foundation's other default colors, but in case it doesn't, we can use Tango's other color groups too.

**Comment by groovecoder** [comment]
Even without styling, just de-styling is starting to look nicer/better ...

![codesy-bids](https://cloud.githubusercontent.com/assets/71928/15100275/d6c031e4-1532-11e6-8a27-84272f98b7d2.png)

**Comment by jdungan** [comment]
Agreed!

**Comment by groovecoder** [comment]
Preview of new styles on widget to make it look more like GitHub ...

![codesy-widget-style](https://cloud.githubusercontent.com/assets/71928/15451938/56e52c26-1fa1-11e6-8977-b37518eacd0d.png)

But I think I've run into a bug with the previous merged code? I wasn't able to get my payout? Or did our PayPal account finally run out of $$?

**Comment by groovecoder** [comment]
Changes still to do:
* [ ] When a user's claim has been approved, show them "Your claim was approved" message and a "Claim your payout" button in the widget, so they can easily and quickly claim their payout.
* [ ] When a user's claim has been paid, show them "Your claim was paid. Thanks for using codesy." message, so they know they don't have to do anything else.
* [ ] When a user needs to vote on a claim, show them a "Vote on the pending claim" button, so they can easily and quickly vote on the claim.
* [ ] When a user has voted on a claim, show them a "You [approved|rejected] [user's] claim.", so they know they don't have to do anything else.
