### ISSUE TITLE
Home landing page updates

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#334]
- [x] Increase padding of top callout section; upper-case text
- [x] Increase margin between `<ol> <li>` elements to make them more read-able

**Comment by TatumCreative** [comment]
* [ ] Padding between sections should feel consistent. 😀

**Comment by TatumCreative** [comment]
Am I contributor now? Will codesy buy me beer?

**Comment by groovecoder** [comment]
Sign up, install the extension and bid on this issue .. I'll offer an amount for you (or anyone) to fix it. 😉
