### ISSUE TITLE
Document steps for manual payout

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#369]
---Includes setting api_success to True

**Comment by jdungan** [comment]
1) Login to admin
2) View Payouts filtered by "requested"

**Comment by groovecoder** [comment]
Between step 3 and 4, we should make it easier to see a payee's email address in the admin.

**Comment by groovecoder** [comment]
While we are using manual payments, PayPal does **NOT** charge $0.25. So, we should send the full amount.

**Comment by groovecoder** [comment]
Closing this out since we're dropping PayPal (& their manual payments).
