### ISSUE TITLE
Get correct ip address for TOS view

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#400]
Stripe require the user ip address be save with the terms of service acceptance.  This is done in the post method on the VerifyIdentityView view in the payments app.  

The line is:

`user.tos_acceptance_ip = self.request.META.get('REMOTE_ADDR')'`
 

This is wrong and returns the ip of the host.

**Comment by groovecoder** [comment]
Ah, yeah we need to use `X-Forwarded-For` header. https://stackoverflow.com/questions/4581789/how-do-i-get-user-ip-address-in-django#4581997
