### ISSUE TITLE
Pages require too many refreshes

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#466]
When a user installs their extension, they have to refresh the page to see the credit card form.

When a user tokenizes their credit card, they have to refresh the page to see the +1 buttons.

**Comment by groovecoder** [comment]
We think this might be Chrome-only?

**Comment by jdungan** [comment]
I've confirm this on Opera and Nightly.  Look like a injection behavior has changed.  May need a brute force 'onInstall' event handler (if this exists).

**Comment by jdungan** [comment]
Was this resolved by https://github.com/codesy/widgets/pull/108

**Comment by groovecoder** [comment]
Yup, these stale pages don't happen anymore.
