### ISSUE TITLE
Account Information Clarity

### ISSUE THREAD

**Issue by aprilchomp** [codesy/codesy#474]
- Need List of CCs and bank accounts on file 

- [ ]  List accounts for 'Change Credit Card'

- [ ] List accounts for 'Change Bank Account'

**Comment by groovecoder** [comment]
Hmm ... we won't be able to list the CC's that are on file, I don't think. Part of using Stripe means we never see the CC #'s. @jdungan do you know if there's a Stripe API call where we can get maybe the last 4 digits of the card or bank accounts?

**Comment by jdungan** [comment]
The last four digits are part of the account object that Stripe returns.  I'll it to the account page.

I'll also try making the submit form collapsed if you've already signed up.
