### ISSUE TITLE
Change /claim-status to show a single payout summary

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#484]
When a user gets paid, only show the summary of the payout sent to their bank account, so they aren't confused by all the individual stripe transactions that added up to their payout.

**Comment by jdungan** [comment]
Test senario:
- user 1 ask for $20
- users 2 and 3 offer $15
- user 1 claims
- 2&3 approve
- user 1 request payout
- payout should show only payout, fees, and total
