### ISSUE TITLE
URI Redirect Error on non www pages

### ISSUE THREAD

**Issue by mrmakeit** [codesy/codesy#506]
When visiting codesy.io instead of www.codesy.io, and attempting to login, the Social Network Login Failure page is displayed with the error "The redirect_uri MUST match the registered callback URL for this application." in the url.

**Comment by groovecoder** [comment]
Interesting, I thought we had a force redirect of all codesy.io traffic to the www domain. That must be broken. :/

**Comment by mrmakeit** [comment]
Just checked. Seems to only happen when logged in.

**Comment by groovecoder** [comment]
This only seems to happen on https://codesy.io - i.e., when the user explicitly visits the *secure* *non-www* domain. (When the user visits insecure domains, we redirect them to `https://www.` ...)

Did you type it in? Or did you visit from a link somewhere? (@jdungan already found one instance of the erroneous link on the Chrome web store)

**Comment by jdungan** [comment]
I've updated all the addon stores for Chrome, Firefox, and Opera to remove the https://codesy.io links.

**Comment by groovecoder** [comment]
Closing this as the source of the bug is fixed. I'll file a new issue to implement HSTS.
