### ISSUE TITLE
Home page should redirect to /payments/card instead of showing CC form

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#507]
When a user installs the extension and then visits the home page without a CC in the database, we should redirect them to `/payments/card`, so they can enter their card info. (Instead of showing them an (out-dated?) CC form directly on the home page.)

**Comment by jdungan** [comment]
I added an interim template called credit_card_row that displays the same cc form as the menu choice (it was the same form but had different styling).

**Comment by groovecoder** [comment]
This is fixed in https://github.com/codesy/codesy/pull/520 (but the commit message had a typo so it didn't auto-fix.)
