### ISSUE TITLE
Claims with invalid URLs fail without error message

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#515]
If the URL provide in a claim is not valid the widget does nothing.  

Recreate:  type www.google.com (without https;//), press claim and nothing happens.

Should: the server returns "please provide a vaild URL"  this should be added to the iframe.

The widget-app attempts this but line 85 fails because 'this' is not the right context.

**Comment by groovecoder** [comment]
This was fixed in https://github.com/codesy/codesy/pull/519#pullrequestreview-66338908 (but the commit message had a typo so it didn't auto-fix.)
