### ISSUE TITLE
widget needs a background when user has no CC#

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#521]
When the widget displays the "You need to register a credit card" message to the user, it has a transparent background which conflicts with the rest of the content on the page.

<img width="215" alt="image" src="https://user-images.githubusercontent.com/71928/31056018-1a6c0ac6-a691-11e7-9b82-c00891d4a35d.png">

**Comment by aprilchomp** [comment]
QA Test PASSED -- Hooray! 

<img width="315" alt="screen shot 2017-10-15 at 2 14 31 pm" src="https://user-images.githubusercontent.com/24953359/31588137-443b9952-b1b3-11e7-9b4b-801849d2632a.png">
