### ISSUE TITLE
The 'extra money offered' example in the FAQ seems erroneous

### ISSUE THREAD

**Issue by Caster** [codesy/codesy#525]
The FAQ has a question **What happens if more money is offered than some asks?** with this example:

> For example, if a dev asks for $5 and there are two offers of $5 and $10 the extra $15 will be split between the three participants.

I read and reread this, but cannot parse this to make it work.

  - Is there one offer of $5 and one of $10?  
    But that would give only $10 extra, because the dev asked for $5 and $15 in total is offered.
  - Are there two offers of $5 and one of $10?  
    That would give $15 extra, but then there would be four participants (three offerors and a claimant).  
    *Also, I argue that the wording is chosen poorly if this is intended.*
  - Are there two offers of $5 and two of $10?  
    But that would give $25 extra, not $15. Also, five participants. Also, poor wording.

Have I overlooked a way of interpreting this sentence?

I propose the following example to be used instead:

*For example, if a dev asks for $5 and there is one offer of $8 and one of $12, the extra $15 will be split evenly between the three participants.*

**Comment by groovecoder** [comment]
I like your proposed text change. @aprilchomp - can you update the text to this:

For example, if a dev asks for $5 and there is one offer of $8 and one of $12, the total offer is $20, and the extra $15 will be split evenly between the three participants.

**Comment by jdungan** [comment]
Agree the this is not clear and suggest a final line to sum it up.

The dev will receive a total of $10 and the offerers will each get a $5 discount.

**Comment by jdungan** [comment]
Fixed by #526.  Thanks @Caster !
