### ISSUE TITLE
Repeating e-mail notifications that asking price has been met

### ISSUE THREAD

**Issue by JosephAMumford** [codesy/codesy#531]
Offer price was met on issue #449.  I've been receiving email notifications every 10 mins since then.

email copy below:

codesy notifications notifications@codesy.io via sendgrid.me 
8:57 PM (7 minutes ago)

to me 

Hi
Great News.  Bidders have met your asking price of $10.00 for https://github.com/codesy/codesy/issues/449.

Your next step is to fix this issue and then claim the payout.

Sincerely,
the codesy.io team

**Comment by jdungan** [comment]
It looks like the message log is corrupted.  I've changed the message state to deferred and added Joseph's email to the 'don't send' list.

**Comment by groovecoder** [comment]
I think I fixed this "for good" by running the db migrations for the mailer app. And I filed https://github.com/codesy/codesy/issues/532 to help prevent errors like this in the future.

Please check that no more messages are coming in; re-open this issue if it's still happening.

Thanks for helping us test!

**Comment by JosephAMumford** [comment]
So far so good, last message received was 8:27 am.
