### ISSUE TITLE
Don't refresh all GitHub tabs every time

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#540]
STR:

1. Open a tab to a GitHub pull request
2. Start a review with some comments
3. Open another tab to a "New Issue" screen
4. Start typing some comment
5. Go to a codesy homepage (e.g., https://127.0.0.1:8443/)

Expected results:
Nothing

Actual results:
The GitHub PR and Issue tabs are both refreshed. Potentially losing data the user entered into them.

We should only refresh `issues/\d+` urls.

**Comment by jdungan** [comment]
@groovecoder This may be a dev only problem since the refresh only occurs when you change codesy domain (e.g. from codesy.io to 127.x).

**Comment by groovecoder** [comment]
Hmm ... did we decide this is not just a dev-only problem?

**Comment by jdungan** [comment]
Yes, but I need to review how/when the widget updates the website.

**Comment by jdungan** [comment]
Fixed in https://github.com/codesy/widgets/pull/120

**Comment by groovecoder** [comment]
Merged, so closing.
