### ISSUE TITLE
Redirect user to final step of onboarding process after success funds are added

### ISSUE THREAD

**Issue by maxxcrawford** [codesy/codesy#545]
## Issue

When a user adds their CC during the second step of the onboarding process, upon success, it displays a success message but does not redirect user to Step 3 of the process until they refresh.

## Steps to reproduce

1. Register as new user
2. Install extension
3. Add valid CC

## Screenshots

*Note – This screenshot technically comes from when a user updates their credit card (after already having registered one). However, the same issues in both states*
![image](https://user-images.githubusercontent.com/2692333/33594001-b3f461f4-d957-11e7-9e0b-4a66cdf6ddbd.png)

**Comment by groovecoder** [comment]
This is fixed now thanks to @KennyTheWizard !
