### ISSUE TITLE
redirect to github log in does not return to issue page or refresh widget

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#579]
The log in with git hub link now opens a new tab with codesy.io site for login.  When this is completed the user is not sent back to their origin tab.

To create:
1. log out of codesy
1. go to an issue
1. click on log in link in widget
1. follow login steps
You will now be on the codesy home page.  If you return to your tab the link will direct you to the codesy tab.  

To fix:
- widget should reload after login
- bonus for returning to the tab

**Comment by groovecoder** [comment]
I'm 90% sure changing tab focus will have to happen in the widget code. Unless we can simply close the codesy.io tab after log-in. But do we want to do that?

**Comment by jdungan** [comment]
This is happening now because of the new check on domain change.  No change, no refresh.  I think our choice is to come up with some type of 'logon' event or figure out the CSP problems that keep from login in the widget.

**Comment by jdungan** [comment]
@groovecoder What can we do with allauth:

`# project/settings.py:
ACCOUNT_ADAPTER = 'project.users.adapter.MyAccountAdapter'

# project/users/adapter.py:
from django.conf import settings
from allauth.account.adapter import DefaultAccountAdapter

class MyAccountAdapter(DefaultAccountAdapter):

    def get_login_redirect_url(self, request):
        path = "/accounts/{username}/"
        return path.format(username=request.user.username)`
