### ISSUE TITLE
Create integration tests

### ISSUE THREAD

**Issue by groovecoder** [codesy/codesy#77]
When I did the DRF 3.0 update, I found some errors only with spot-checking. So, we should create a higher-level suite of tests that test the key user flows that integrate many pieces:
- [ ] Test that user registration creates an authorization token
- [ ] Test that GET, POST, PUT, and DELETE of bids (via [BidViewSet](https://github.com/codesy/codesy/blob/master/auctions/views.py)) work as expected
- [ ] Test that GETting the bid widget HTML (via [GetBid APIView](https://github.com/codesy/codesy/blob/master/auctions/views.py)) works as expected

**Comment by jdungan** [comment]
OBE
