### ISSUE TITLE
Don't return bid form when issue is closed

### ISSUE THREAD

**Issue by jdungan** [codesy/codesy#97]
GET /bid returns a form for POST or PUT bids.  Need to reply with information that the issue was closed.

**Comment by groovecoder** [comment]
I thought about using the `Issue` model for this, but there's some lag between someone closing the issue on GitHub and when [our `update_issue_states` cron util](https://github.com/codesy/codesy/blob/master/auctions/utils.py) will update the `Issue` status in codesy.

So, I wonder if the widget should detect the state and send an extra url parameter to indicate the state? E.g., https://codesy.io/bid/?url=https://github.com/codesy/codesy/issues/97&state=closed That adds more logic to the widget, but ensures the widget always gets the right form to display.

What do you think @jdungan ?

**Comment by jdungan** [comment]
Here's the challenge:  the url for issues is the same whether opened or closed.  There are a few indicators on the pages but they are transient (e.g. <div class="state state-closed">).  Easy enough to detect for now, but we'll need to find a more reliable way.

**Comment by groovecoder** [comment]
Okay, my other idea is to move the [`update_bid_issues`](https://github.com/codesy/codesy/blob/master/auctions/utils.py#L36-L44) code into a `post_save` signal handler on `Bid`. The request to save the first bid on an issue will be coupled to a corresponding HTTP request back to GitHub, but that seems better than the lag or un-reliable HTML scraping. What do you think?

**Comment by jdungan** [comment]
I don't want to give up the idea of the widget recognizing the closed issue.  Using the widget will make the experience more realtime.  I'd eventually like to add a message to all active widgets so they 'close'

We just need to recognize the tech debt of keeping up with a state indicator on github.
